### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by SamuelBismuth** [SamuelBismuth/Betitarev#1]
@yoshago, could you perhaps explain to me how did you fix the fragment problem?
Since I saw that you solved the problem by using the content xml I'm pretty sure I could do the same with the place a bet fragment. My purpose is to handle the xml file.

**Comment by yoshago** [comment]
@SamuelBismuth the problem was that I copied some code from the login activity to the main activity and there was the function finish(); which caused the crash in the profile fragment.
about the xml. I do not think there is a actual differece between the content and the activity xmls, besides proper engineering.

**Comment by SamuelBismuth** [comment]
@yoshago , thanks for the reply.
Could you be clearer: where does the code should be writing, and where should I handle all the xml features: in the main activity, or in the fragment activity?
